import { Gift, Heart, Sparkles } from "lucide-react";
import useScrollReveal from "../../hooks/useScrollReveal";

const messages = [
    {
        type: "Birthday",
        recipient: "Mom",
        message: "Happy Birthday, Mom! 🎂 Your love has been my guiding light through every challenge. Here's to another year of your warmth, wisdom, and wonderful hugs. I love you more than words can say!",
        gradient: "from-pink-500/20 to-orange-500/20",
        borderColor: "border-pink-500/30",
    },
    {
        type: "Anniversary",
        recipient: "Partner",
        message: "3 years ago, I found my favorite adventure partner. Every day with you is a gift I'll never stop being grateful for. Here's to us, to our journey, and to forever. I love you endlessly! 💕",
        gradient: "from-primary/20 to-secondary/20",
        borderColor: "border-primary/30",
    },
    {
        type: "Festival",
        recipient: "Friend",
        message: "Happy Diwali, buddy! 🪔 May this festival of lights illuminate your path to success and happiness. Wishing you prosperity, good health, and countless moments of joy!",
        gradient: "from-amber-500/20 to-yellow-500/20",
        borderColor: "border-amber-500/30",
    },
];

const cardDesigns = [
    {
        title: "Birthday Celebration",
        gradient: "from-pink-600 to-purple-600",
        icon: Gift,
    },
    {
        title: "Anniversary Love",
        gradient: "from-rose-500 to-pink-500",
        icon: Heart,
    },
    {
        title: "Festival Wishes",
        gradient: "from-amber-500 to-orange-500",
        icon: Sparkles,
    },
];

const MessageShowcase = () => {
    const { ref: headerRef, isVisible: headerVisible } = useScrollReveal();
    const { ref: messagesRef, isVisible: messagesVisible } = useScrollReveal({ threshold: 0.1 });
    const { ref: cardsHeaderRef, isVisible: cardsHeaderVisible } = useScrollReveal();
    const { ref: cardsRef, isVisible: cardsVisible } = useScrollReveal({ threshold: 0.1 });

    return (
        <section className="relative py-24 overflow-hidden">
            <div className="absolute inset-0 bg-gradient-to-b from-background to-muted/20" />

            <div className="relative z-10 max-w-7xl mx-auto px-6">
                <div
                    ref={headerRef as React.RefObject<HTMLDivElement>}
                    className={`text-center space-y-4 mb-16 scroll-reveal ${headerVisible ? 'visible' : ''}`}
                >
                    <span className="inline-block px-4 py-1.5 rounded-full text-sm font-medium bg-secondary/10 text-secondary border border-secondary/20">
                        AI Magic
                    </span>
                    <h2 className="text-3xl sm:text-4xl lg:text-5xl font-display font-bold">
                        See <span className="gradient-text">AI-Crafted</span> Messages
                    </h2>
                    <p className="text-lg text-muted-foreground max-w-2xl mx-auto">
                        Every message is unique, personal, and perfectly timed.
                    </p>
                </div>

                {/* Messages showcase */}
                <div
                    ref={messagesRef as React.RefObject<HTMLDivElement>}
                    className={`grid lg:grid-cols-3 gap-6 mb-16 scroll-reveal-stagger ${messagesVisible ? 'visible' : ''}`}
                >
                    {messages.map((msg) => (
                        <div
                            key={msg.type}
                            className={`relative glass-card p-6 ${msg.borderColor} hover:scale-105 transition-all duration-300`}
                        >
                            {/* Header */}
                            <div className="flex items-center justify-between mb-4">
                                <span className={`px-3 py-1 rounded-full text-xs font-medium bg-gradient-to-r ${msg.gradient}`}>
                                    {msg.type}
                                </span>
                                <span className="text-sm text-muted-foreground">To: {msg.recipient}</span>
                            </div>

                            {/* Message bubble */}
                            <div className="bg-muted/30 rounded-2xl rounded-tl-none p-4 border border-border/50">
                                <p className="text-foreground text-sm leading-relaxed">
                                    {msg.message}
                                </p>
                            </div>

                            {/* AI badge */}
                            <div className="flex items-center gap-2 mt-4 text-xs text-muted-foreground">
                                <Sparkles className="w-3 h-3 text-primary" />
                                <span>Generated by SoulSync AI AI</span>
                            </div>

                            {/* Glow effect */}
                            <div className={`absolute -inset-0.5 rounded-2xl bg-gradient-to-r ${msg.gradient} opacity-0 hover:opacity-20 transition-opacity duration-300 -z-10 blur-xl`} />
                        </div>
                    ))}
                </div>

                {/* Card designs preview */}
                <div
                    ref={cardsHeaderRef as React.RefObject<HTMLDivElement>}
                    className={`text-center mb-8 scroll-reveal ${cardsHeaderVisible ? 'visible' : ''}`}
                >
                    <h3 className="text-2xl font-display font-semibold text-foreground mb-2">
                        Auto-Generated Greeting Cards
                    </h3>
                    <p className="text-muted-foreground">Beautiful designs created automatically for every occasion</p>
                </div>

                <div
                    ref={cardsRef as React.RefObject<HTMLDivElement>}
                    className={`grid sm:grid-cols-3 gap-6 max-w-3xl mx-auto scroll-reveal-stagger ${cardsVisible ? 'visible' : ''}`}
                >
                    {cardDesigns.map((card) => (
                        <div
                            key={card.title}
                            className="group relative aspect-[3/4] rounded-2xl overflow-hidden cursor-pointer"
                        >
                            <div className={`absolute inset-0 bg-gradient-to-br ${card.gradient}`} />
                            <div className="absolute inset-0 bg-[linear-gradient(45deg,transparent_25%,rgba(255,255,255,0.1)_50%,transparent_75%)] bg-[length:200%_200%] group-hover:animate-shimmer" />

                            <div className="absolute inset-0 flex flex-col items-center justify-center text-white p-6">
                                <card.icon className="w-12 h-12 mb-4 drop-shadow-lg" />
                                <h4 className="text-lg font-semibold text-center drop-shadow-lg">{card.title}</h4>
                            </div>

                            {/* Border glow */}
                            <div className="absolute inset-0 rounded-2xl border border-white/20 group-hover:border-white/40 transition-colors" />
                        </div>
                    ))}
                </div>
            </div>
        </section>
    );
};

export default MessageShowcase;
